from PyQt6 import QtCore

key_map = {
            QtCore.Qt.Key.Key_A: 'C2',
            QtCore.Qt.Key.Key_S: 'D2',
            QtCore.Qt.Key.Key_D: 'E2',
            QtCore.Qt.Key.Key_F: 'F2',
            QtCore.Qt.Key.Key_G: 'G2',
            QtCore.Qt.Key.Key_H: 'A2',
            QtCore.Qt.Key.Key_J: 'B2',
            QtCore.Qt.Key.Key_K: 'C3',
            QtCore.Qt.Key.Key_W: 'C2H',
            QtCore.Qt.Key.Key_E: 'D2H',
            QtCore.Qt.Key.Key_T: 'F2H',
            QtCore.Qt.Key.Key_Y: 'G2H',
            QtCore.Qt.Key.Key_U: 'A2H',
            QtCore.Qt.Key.Key_Z: 'C3',
            QtCore.Qt.Key.Key_X: 'D3',
            QtCore.Qt.Key.Key_C: 'E3',
            QtCore.Qt.Key.Key_V: 'F3',
            QtCore.Qt.Key.Key_B: 'G3',
            QtCore.Qt.Key.Key_N: 'A3',
            QtCore.Qt.Key.Key_M: 'B3',
            QtCore.Qt.Key.Key_3: 'C3H',
            QtCore.Qt.Key.Key_4: 'D3H',
            QtCore.Qt.Key.Key_6: 'F3H',
            QtCore.Qt.Key.Key_7: 'G3H',
            QtCore.Qt.Key.Key_8: 'A3H',
        }
